language: ruby
rvm:
  - 2.6.2
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake test:db
  - bundle exec rake test:system
services:
  - postgresql
notifications:
  email: false
