language: ruby
rvm:
  - 2.6.2
before_script:
  - bundle update --bundler
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake test:db
  - bundle exec rake test:system
services:
  - postgresql
notifications:
email: false

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
